name: Angular App CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Initialize Dependencies
        run: |
          cd Oblivion
          npm ci

      - name: Test in Chrome Browser
        run: |
          cd Oblivion
          npm run test-headless-chrome
        env:
          CI: true

      - name: Build Angular App
        run: |
          cd Oblivion
          npm run build --if-present
